spring.application.name=HotelService

server.port = 8082

spring.datasource.url = jdbc:postgresql://localhost:5432/microservice_hotel
spring.datasource.username = postgres
spring.datasource.password = Welcome@1234$

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update